"""
servers/risk_engine/tools/garch_forecast.py

Implementation of the compute_garch_forecast tool.

Responsibilities:
    - Fit a GARCH(1,1) model with Student-t innovations to each asset's
      log-return series via Maximum Likelihood Estimation (MLE)
    - Extract current conditional volatility σ_T (end of historical window)
    - Produce deterministic forward volatility term structure σ_{T+1}..σ_{T+H}
    - Classify current volatility regime vs long-run unconditional volatility
    - Assemble handoff fields for the Scenario Simulation Server

V1 Modelling Assumptions (see README.md for full rationale):
    Mean equation:    Constant mean — zero drift assumed for daily log-returns
                      Daily equity log-returns are close to a martingale.
                      ARMA mean dynamics deferred to v2.

    Variance equation: GARCH(1,1) — fixed order, industry standard for
                       daily equity data. Not auto-selected in v1.
                       σ²_t = ω + α·ε²_{t-1} + β·σ²_{t-1}

    Innovations:      Student-t with empirically fitted degrees of freedom ν
                      Captures excess kurtosis (fat tails) in NSE equity returns.

    Stationarity:     I=0 assumed — log-returns are already I(0) by construction
                      (first difference of log-prices).

V2 Plans:
    - Replace constant mean with ARMA(p,q), auto-select order via AIC/BIC
    - Add auto_order flag for GARCH order selection
    - Add skewed Student-t innovations option

This file contains pure computation logic only.
No MCP protocol code — that lives in server.py.

Two phases (both in this file):
    Phase 1 — Estimation (backward-looking):
        Fits {ω, α, β, ν} from historical log-returns via MLE.
        Runs GARCH recursion through history to recover σ_T.

    Phase 2 — Forecasting (forward-looking):
        Uses fitted parameters to project deterministic expected vol path.
        σ²_{T+h} = longrun_var + (α+β)^h × (σ²_T - longrun_var)
        This is the MEAN of future volatility — not a stochastic path.
        Stochastic paths are generated by run_garch_simulation in Simulator.

Handoff to Simulator:
    garch_params  — fitted {ω, α, β, ν} per asset
    current_vols  — σ_T per asset (starting point for simulation)
    These fields are consumed by run_garch_simulation via AgentState.
"""

from __future__ import annotations

import warnings
from typing import Any

import numpy as np

# arch library — Kevin Sheppard's ARCH/GARCH package
# statsmodels is a transitive dependency pulled in automatically
from arch import arch_model

# ── Constants ─────────────────────────────────────────────────────────────────
TRADING_DAYS_PER_YEAR = 252

# Regime classification thresholds
# current_vol > longrun_vol × ELEVATED_THRESHOLD → "elevated"
# current_vol < longrun_vol × SUPPRESSED_THRESHOLD → "suppressed"
ELEVATED_THRESHOLD   = 1.25
SUPPRESSED_THRESHOLD = 0.75

# Persistence warning threshold
# alpha + beta >= this value → model is near non-stationary
PERSISTENCE_WARNING_THRESHOLD = 1.0

# Minimum observations required for reliable GARCH fitting
MIN_OBSERVATIONS = 100

# Valid model and innovation types
VALID_MODELS     = {"garch", "egarch", "gjr_garch"}
VALID_INNOVATIONS = {"student_t", "gaussian"}


# ── Phase 1: Model fitting ────────────────────────────────────────────────────

def _fit_garch_model(
    returns: np.ndarray,
    model: str,
    innovations: str,
) -> Any:
    """
    Fit a GARCH model to a return series via MLE.

    Uses the arch library's arch_model interface.
    Mean equation is constant (V1 assumption — see module docstring).

    Model types:
        "garch"     → standard GARCH(1,1): σ²_t = ω + α·ε²_{t-1} + β·σ²_{t-1}
        "egarch"    → EGARCH(1,1): captures leverage effect (negative shocks
                      increase volatility more than positive shocks)
        "gjr_garch" → GJR-GARCH(1,1): asymmetric response to positive/negative shocks

    Innovation distributions:
        "student_t" → Student-t with fitted ν — captures fat tails
        "gaussian"  → Normal — baseline comparison

    Args:
        returns:     np.ndarray — daily log-returns, length T
        model:       str — "garch" | "egarch" | "gjr_garch"
        innovations: str — "student_t" | "gaussian"

    Returns:
        arch ModelResult object — contains fitted parameters and diagnostics

    Raises:
        RuntimeError: if MLE optimisation fails to converge
    """
    # Map our model names to arch library identifiers
    vol_map = {
        "garch":     "GARCH",
        "egarch":    "EGARCH",
        "gjr_garch": "GARCH",   # GJR-GARCH uses GARCH vol with o=1 parameter
    }

    dist_map = {
        "student_t": "t",
        "gaussian":  "Normal",
    }

    # Scale returns to percentage — arch library works more stably with
    # returns expressed as percentages (e.g. 1.5 instead of 0.015)
    returns_pct = returns * 100

    am = arch_model(
        returns_pct,
        mean="Constant",
        vol=vol_map[model],
        p=1,
        o=1 if model == "gjr_garch" else 0,  # asymmetry term for GJR
        q=1,
        dist=dist_map[innovations],
    )

    # Suppress convergence warnings during fitting — we check convergence manually
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        result = am.fit(disp="off", show_warning=False)

    # Check convergence
    if result.convergence_flag != 0:
        raise RuntimeError(
            f"GARCH model did not converge (flag={result.convergence_flag}). "
            f"Try a longer return series or different model specification."
        )

    return result


def _extract_params(result: Any, innovations: str) -> dict:
    """
    Extract fitted GARCH parameters from arch ModelResult.

    Parameters returned by arch are in percentage-scaled space.
    We convert omega back to return-scale (divide by 100²).
    Alpha and beta are dimensionless ratios — no scaling needed.

    Args:
        result:      arch ModelResult
        innovations: str — needed to extract ν for Student-t

    Returns:
        dict with keys: omega, alpha, beta, nu (None for gaussian)
    """
    params = result.params

    # omega is the GARCH intercept — in percentage-squared space
    # convert back to return-scale: divide by 100^2
    omega = float(params["omega"]) / (100 ** 2)
    alpha = float(params["alpha[1]"])
    beta  = float(params["beta[1]"])

    # Student-t degrees of freedom — only for Student-t innovations
    nu = None
    if innovations == "student_t":
        nu = float(params["nu"])

    return {
        "omega": omega,
        "alpha": alpha,
        "beta":  beta,
        "nu":    nu,
    }


def _get_current_vol(result: Any) -> float:
    """
    Extract current conditional volatility σ_T from fitted model.

    The arch library computes conditional volatility for each observation
    during fitting. The last value is σ_T — the volatility state at the
    end of the historical window.

    Returns annualised volatility:
        σ_T_annualised = σ_T_daily × √252

    The conditional_volatility from arch is in percentage-daily units.
    We convert: divide by 100 (back to return scale) then annualise.

    Args:
        result: arch ModelResult

    Returns:
        float — current annualised conditional volatility
    """
    # Last value of conditional volatility series (percentage-daily)
    sigma_T_pct_daily = float(result.conditional_volatility[-1])

    # Convert to return-scale daily, then annualise
    sigma_T_daily = sigma_T_pct_daily / 100
    sigma_T_annual = sigma_T_daily * np.sqrt(TRADING_DAYS_PER_YEAR)

    return sigma_T_annual


# ── Phase 2: Volatility forecasting ──────────────────────────────────────────

def _compute_longrun_vol(omega: float, alpha: float, beta: float) -> float:
    """
    Compute long-run (unconditional) volatility from GARCH parameters.

    longrun_var = ω / (1 - α - β)
    longrun_vol = √(longrun_var) × √252  (annualised)

    This is the level that σ_t mean-reverts toward over the forecast horizon.
    When α + β is close to 1, mean reversion is slow (high persistence).
    When α + β is far from 1, mean reversion is fast.

    Args:
        omega: float — GARCH intercept (return-scale)
        alpha: float — ARCH term
        beta:  float — GARCH term

    Returns:
        float — annualised long-run volatility

    Raises:
        ValueError: if alpha + beta >= 1 (non-stationary model)
    """
    persistence = alpha + beta

    if persistence >= 1.0:
        raise ValueError(
            f"GARCH model is non-stationary: α + β = {persistence:.4f} ≥ 1. "
            f"Long-run variance is undefined. "
            f"Consider a shorter estimation window or IGARCH specification."
        )

    longrun_var_daily = omega / (1.0 - persistence)
    longrun_vol_annual = np.sqrt(longrun_var_daily) * np.sqrt(TRADING_DAYS_PER_YEAR)

    return float(longrun_vol_annual)


def _compute_vol_forecast(
    omega: float,
    alpha: float,
    beta: float,
    current_vol_annual: float,
    horizon_days: int,
) -> list[float]:
    """
    Compute deterministic GARCH volatility term structure.

    Uses the GARCH mean-reversion formula:
        σ²_{T+h} = longrun_var + (α+β)^h × (σ²_{T} - longrun_var)

    This is the EXPECTED (mean) volatility path — not a stochastic simulation.
    It shows where volatility is headed on average if no new shocks arrive.

    Properties:
        h=0:        σ²_{T+0} = σ²_T (current state)
        h→∞:        σ²_{T+h} → longrun_var (mean reversion)
        α+β close to 1: slow mean reversion (elevated vol persists)
        α+β far from 1: fast mean reversion (vol quickly returns to average)

    Args:
        omega:              float — GARCH intercept (return-scale)
        alpha:              float — ARCH term
        beta:               float — GARCH term
        current_vol_annual: float — σ_T annualised (starting point)
        horizon_days:       int   — number of steps to forecast

    Returns:
        list[float] — annualised volatility forecast σ_{T+1}..σ_{T+H}
                      length = horizon_days
    """
    persistence  = alpha + beta
    longrun_var  = omega / (1.0 - persistence)

    # Convert current annualised vol back to daily variance for recursion
    current_var_daily = (current_vol_annual / np.sqrt(TRADING_DAYS_PER_YEAR)) ** 2

    forecasts = []
    for h in range(1, horizon_days + 1):
        # GARCH mean-reversion formula
        var_Th = longrun_var + (persistence ** h) * (current_var_daily - longrun_var)

        # Guard against numerical issues (negative variance)
        var_Th = max(var_Th, 1e-10)

        # Annualise
        vol_Th = np.sqrt(var_Th) * np.sqrt(TRADING_DAYS_PER_YEAR)
        forecasts.append(float(vol_Th))

    return forecasts


def _compute_regime(current_vol: float, longrun_vol: float) -> str:
    """
    Classify current volatility regime relative to long-run average.

    Thresholds (configurable via module constants):
        elevated:   current_vol > longrun_vol × 1.25
        suppressed: current_vol < longrun_vol × 0.75
        normal:     otherwise

    Args:
        current_vol: float — σ_T annualised
        longrun_vol: float — unconditional annualised volatility

    Returns:
        str — "elevated" | "normal" | "suppressed"
    """
    if current_vol > longrun_vol * ELEVATED_THRESHOLD:
        return "elevated"
    elif current_vol < longrun_vol * SUPPRESSED_THRESHOLD:
        return "suppressed"
    else:
        return "normal"


# ── Main tool function ────────────────────────────────────────────────────────

def compute_garch_forecast(
    log_returns: dict[str, list[float]],
    horizon_days: int = 21,
    model: str = "garch",
    innovations: str = "student_t",
) -> dict:
    """
    Fit GARCH(1,1) to each asset and produce volatility forecasts.

    This is the implementation of the compute_garch_forecast MCP tool.
    Called by server.py — never called directly by other servers.

    Two phases:
        Phase 1 (backward-looking): MLE estimation on historical data
        Phase 2 (forward-looking):  Deterministic vol term structure

    The output garch_params and current_vols fields are consumed directly
    by run_garch_simulation in the Scenario Simulation Server via AgentState.
    The Simulator does not re-fit the model — it uses these parameters.

    Args:
        log_returns:  dict[symbol, list[float]] — from Market Data Server
        horizon_days: int — forecast horizon, default 21 (1 month)
        model:        str — "garch" | "egarch" | "gjr_garch"
        innovations:  str — "student_t" | "gaussian"

    Returns:
        dict matching GARCHResult schema in orchestrator/state.py

    Raises:
        ValueError: if model or innovations is invalid
        ValueError: if any symbol has insufficient observations
        RuntimeError: if GARCH fitting fails to converge for any symbol
    """
    # ── Input validation ──────────────────────────────────────────
    if model not in VALID_MODELS:
        raise ValueError(
            f"Invalid model '{model}'. Must be one of: {VALID_MODELS}"
        )

    if innovations not in VALID_INNOVATIONS:
        raise ValueError(
            f"Invalid innovations '{innovations}'. "
            f"Must be one of: {VALID_INNOVATIONS}"
        )

    if horizon_days < 1:
        raise ValueError(
            f"horizon_days must be >= 1, got {horizon_days}"
        )

    if not log_returns:
        raise ValueError("log_returns dict must not be empty")

    # ── Fit GARCH per asset ───────────────────────────────────────
    per_asset = {}
    garch_params = {}
    current_vols = {}

    for symbol, returns_list in log_returns.items():
        returns = np.array(returns_list, dtype=float)

        if len(returns) < MIN_OBSERVATIONS:
            raise ValueError(
                f"Symbol {symbol} has {len(returns)} observations — "
                f"minimum {MIN_OBSERVATIONS} required for reliable GARCH fitting."
            )

        # Phase 1 — Estimation
        result      = _fit_garch_model(returns, model, innovations)
        params      = _extract_params(result, innovations)
        current_vol = _get_current_vol(result)

        omega = params["omega"]
        alpha = params["alpha"]
        beta  = params["beta"]
        nu    = params["nu"]

        alpha_plus_beta     = alpha + beta
        persistence_warning = alpha_plus_beta >= PERSISTENCE_WARNING_THRESHOLD

        # Long-run volatility — handle near-non-stationary case gracefully
        try:
            longrun_vol = _compute_longrun_vol(omega, alpha, beta)
        except ValueError:
            # alpha + beta >= 1 — use current vol as longrun proxy
            longrun_vol = current_vol
            persistence_warning = True

        # Phase 2 — Forecasting
        vol_forecast = _compute_vol_forecast(
            omega, alpha, beta, current_vol, horizon_days
        )

        # Regime classification
        regime = _compute_regime(current_vol, longrun_vol)

        # AIC and BIC from arch result
        aic = float(result.aic)
        bic = float(result.bic)

        per_asset[symbol] = {
            "params": {
                "omega": omega,
                "alpha": alpha,
                "beta":  beta,
                "nu":    nu,
            },
            "alpha_plus_beta":     alpha_plus_beta,
            "current_vol":         current_vol,
            "longrun_vol":         longrun_vol,
            "vol_forecast":        vol_forecast,
            "regime":              regime,
            "aic":                 aic,
            "bic":                 bic,
            "persistence_warning": persistence_warning,
        }

        # Handoff fields for Simulator
        garch_params[symbol] = {
            "omega": omega,
            "alpha": alpha,
            "beta":  beta,
            "nu":    nu,
        }
        current_vols[symbol] = current_vol

    # ── Portfolio vol forecast ────────────────────────────────────
    # Equal-weighted average of per-asset vol forecasts
    # Static correlation — DCC-GARCH deferred to v3
    symbols = list(per_asset.keys())
    n_assets = len(symbols)
    portfolio_vol_forecast = []

    for h in range(horizon_days):
        avg_vol = sum(
            per_asset[s]["vol_forecast"][h] for s in symbols
        ) / n_assets
        portfolio_vol_forecast.append(avg_vol)

    return {
        "per_asset":              per_asset,
        "portfolio_vol_forecast": portfolio_vol_forecast,
        "garch_model":            model,
        "innovations_used":       innovations,
        "horizon_days":           horizon_days,
        "garch_params":           garch_params,
        "current_vols":           current_vols,
    }